spring.application.name=demo
#spring.security.user.name=user
#spring.security.user.password={bcrypt}$2y$10$1UV0GXMh9dOXvUWVTc2kCOdQtfvZbxsWSxwXpl1.ACwXg2Vv.FgTa
jwt.secret=abcdefghijklmnopqrstuvwxyz1234567890ABCD1?????????????????????